trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: First_Job
        steps:
          - bash: echo Hi
      - job: Second_job
        steps:
          - bash: echo done
  - stage: Deploy
    jobs:
      - job: First_Job
        steps:
          - bash: echo Hi
      - job: Second_job
        steps:
          - bash: echo done
    


